version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.2
    container_name: filebeat
    user: root
    restart: unless-stopped
    network_mode: host  # Required to access host network for Suricata and other services
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/wazuh:/var/log/wazuh:ro
      - /var/log/suricata:/var/log/suricata:ro
      - /var/log/thehive:/var/log/thehive:ro
      - /var/log/cortex:/var/log/cortex:ro
      - /var/log/misp:/var/log/misp:ro
      - /var/log:/var/log/system:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat-data:/usr/share/filebeat/data
    environment:
      - ELASTICSEARCH_HOSTS=http://wazuh.indexer:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=SecretPassword
      - SETUP_ILM=true
    depends_on:
      - wazuh.indexer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5066"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  filebeat-data:
    driver: local
