version:
  name: velociraptor
  version: 0.7.1
  commit: "0746831"
  build_time: "2023-12-13T10:45:43Z"
  install_time: 1750299027
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7194076107
  compiler: go1.21.4
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRANfOIMi4la56ANduIMRVPOAwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDYxOTAyMTAyN1oXDTM1
    MDYxNzAyMTAyN1owGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsR0YTxagalVg9Koimt/uWXsblvKNFg0u
    TRfuBCEAs/ySfWghmQPi06ROmtEW0Tlv3C9ra8zD4kh5CyVSuf2ZNXoAmbGqoEFA
    LxxTn5mvMiEYmgRH9u8nICwOhyYVS++98+H6Y3D2OW1x8ct03Y+cIvEyoMYBk8Yt
    osqfpPvjQ3wHiWlMQSg5NVrLNuQKGfcGoEtUm420kAspRc39Z0zj+VAnDwDtBuaS
    u14GorXwXVhAl/Tl/gRWVPFOePM57+HvDBYpTRH8+6yBfmDBpq8fwg0jnr05ed9k
    SPGQm0w37A6mHKyxwrsdt3f2OTYdrPqth02f4vMjXXxo63PoVBBEtQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUSS3DEBSJ7lM0HsmODfWSo2EP
    ygwwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAIN8/vsZLGJBC+jsV7+f+d4sZ2yaEBVG57K3jpeHjXEg
    rcMjPyjzgwUX0FHVgFFo1fTso64AnX9+3FS3iv13PGPjhM1f2/pi+UZrdbhssyGg
    J5tEELu3TWysAa9p4M3Dso6xrBc+Rs6P5S2nHQg5cYxoHlXBVS6vx4KYOuO36eTC
    KgxrW/NlbschDZEfTkRYJEqyAeKGOpktBAk1sC3BizenIO7Xf5qyb92ZirvqVKuS
    qP1/JjbH139h6ep75EGZ/DQLabR03jGgrXu8Ov6tv/YQ8s4AnBilq0FpiwMkKqun
    jyX1e1hPzpS8MEikOIczF+Ck03OYHvzsO9kz99ja+kc=
    -----END CERTIFICATE-----
  nonce: n2Hag60gGWQ=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.1
    commit: "0746831"
    build_time: "2023-12-13T10:45:43Z"
    install_time: 1750299027
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7194076107
    compiler: go1.21.4
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 0.0.0.0
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 0.0.0.0
  bind_port: 8889
  public_url: https://172.31.34.5:7000/app/index.html
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIQUlnmDmTnVTvAkKIigBjMdjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwNjE5MDIxMDI3WhcNMjYw
    NjE5MDIxMDI3WjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS
    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQ1Edvzz1I1DUt
    iCCNIIbiGQrTYDqcp3MqHCHMTbMImO+6EU/2eiNG3aaDWyVdDJM6JcV68bp2GigF
    yPrDs/MfIBbg3S76FINKEOFWvxTMjHkMhb81z5xvYGRV2Jxgs8i1ivLBREoOKG/e
    WLZrNRlskWczpAP+74lZkoHGfwvDyRxflOBL2gv4eXQA2QMWhomOFO2MjxvYXSd9
    gnT/w64wCqQAe70sW7xq5OTvXxpyWMNbdjYMWls4td43nYZ7kiIy/GvbotqAsyQD
    wEAYQ3C8vfiMCjsNag2+NuztmoApCj5Zbrp1tJQUbpiwXHh4XS6nBgQ3TO3/4Kwb
    4MUfG/llAgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRJLcMQFInu
    UzQeyY4N9ZKjYQ/KDDASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA
    A4IBAQAWSREtYmvdkrPA604xYci/fsFTrEVUtJbQX9+5eRpx5I9UqbENMPNYlgVu
    NBb0TmXlzqX2k03SaQi6AWX3os0AJ1mNUju+/ofcVFYeVSao3nrqtO3wXr0UdZ4g
    C8aSp9HfpKTBlk5YKLMrqGlIxV19kB5TanjeAYizJSF4s+Vead24PNwAR7A+Y/HQ
    7NbUDF/ar/HjEekyKduQDm8u+/n7jUJFkFqR/0q7bM/jlZDZMFMYI10rZD8lpAgk
    5kGBalWacNXwJcijKLSxHPDPQ/mNHm7LdS7HVoY2KVPvLNz4dF7YVJyamDfFzzbM
    RqWEv0jUx1TC7p19lJhkEdVJc2Hv
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA0NRHb889SNQ1LYggjSCG4hkK02A6nKdzKhwhzE2zCJjvuhFP
    9nojRt2mg1slXQyTOiXFevG6dhooBcj6w7PzHyAW4N0u+hSDShDhVr8UzIx5DIW/
    Nc+cb2BkVdicYLPItYrywURKDihv3li2azUZbJFnM6QD/u+JWZKBxn8Lw8kcX5Tg
    S9oL+Hl0ANkDFoaJjhTtjI8b2F0nfYJ0/8OuMAqkAHu9LFu8auTk718acljDW3Y2
    DFpbOLXeN52Ge5IiMvxr26LagLMkA8BAGENwvL34jAo7DWoNvjbs7ZqAKQo+WW66
    dbSUFG6YsFx4eF0upwYEN0zt/+CsG+DFHxv5ZQIDAQABAoIBAQCp4NYQJbVEBqUP
    2hoo1BoF2btNwo1LnIh57BKugVKwHsF9StISvr7tyifH2aCmdjFabxmb7wLxSkve
    kOU1yLBxVIhn+mZZt9Aps1usVpsT3v4l6rNmkfI/RFm64BAuNnKDBHqAMA5SQCDo
    7p/OzI5XHF2oy7cYb0H7ZMw/bmBirkD4wANDC19UxU4f/r82XeRw0h22nZEhL6hb
    u/1LF0bPFT+YvDg8DDQZfi9gtP+k9goUAcByenRkV+h1tV7kengv8pJGby5N+Cj3
    of/jQS+Wf/Eear3RpeY6+OIHfOfMK7T6I1Xus9HmfCJTVMifEyNa3NPqwwIA9/p9
    CCJVPcwhAoGBAPsaxMAsFRxSE12MhuauHRqsV7Z7eg4clDOwPd5x82ajfrP+br/T
    6z62NJHn4CpyBrrOar3LQfgPe+inxxIhEsdFMhVxVXAjzPFvtE8+Anop5faC5DTS
    YQjyqrOudCQ9I1u1KBxcrG0iUrll7Sg0eOVmueXDWCK39JEq/TB2iAoZAoGBANTm
    hP741ARSOXSHyH6K1e5xnRuFGRG3Jvg2e+U8gtTMRX3NJSIlOc1iURmPvb5nQQZu
    4WnC4S5rMA3SkwnpfBKFIrlKKpbMXd59WTqFYYyVlUTmRgSOxVoXNHD8C2jqNZAG
    5i6b00a6Q2934jUI4hln3RFtdHTn3dY40AfbgCstAoGAJToOuT7P0mcIn/HZfhGK
    Fw494rvjmHv8LL2QLo5OO4U5n4209ZOBaMayfH8X6LMG9GLtyD1+BjylbhSRmsp0
    cj578lnfBMUJ+TFKVgUncN0NTsKQ+pPF9wGi9QiEB2tY9pug2rOSjItuIDZQNomw
    8rGMFdgkFOGYzHzHFIw+FuECgYEAtbOMHIRHhuyaJq9gWUeqr9d9a6hbrffvpXXy
    pcHQM0eno2d7Yrn8rCJV7wfzu9Yp9BCcB4SQZOqMV6+5WINSJghEi3kWAh+nmaTH
    i5+ckrxzahtR9L/ZBTu6wRcLsd36GtMYjvzlA38i4Lajc/oB5gbz8NTGyKO/e/5+
    5cXbjH0CgYEA2TimBOYDwIcezjgt2Cr7HEP+3uUIUySHfuyvmWPTS/cUsKc+pMdm
    GrVAqtRF4t6jARcQ/jN4aZ2Hh4eUnRmuA36SBow0uJ98uF1RyRzC+Jl/C3yEnN3K
    C8IDYv6Cy8+/QQcesNc2QCsUzUYVMTYQ8CTUD8rhw2LFsvDeonnIn7Y=
    -----END RSA PRIVATE KEY-----
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAsR0YTxagalVg9Koimt/uWXsblvKNFg0uTRfuBCEAs/ySfWgh
    mQPi06ROmtEW0Tlv3C9ra8zD4kh5CyVSuf2ZNXoAmbGqoEFALxxTn5mvMiEYmgRH
    9u8nICwOhyYVS++98+H6Y3D2OW1x8ct03Y+cIvEyoMYBk8YtosqfpPvjQ3wHiWlM
    QSg5NVrLNuQKGfcGoEtUm420kAspRc39Z0zj+VAnDwDtBuaSu14GorXwXVhAl/Tl
    /gRWVPFOePM57+HvDBYpTRH8+6yBfmDBpq8fwg0jnr05ed9kSPGQm0w37A6mHKyx
    wrsdt3f2OTYdrPqth02f4vMjXXxo63PoVBBEtQIDAQABAoIBAGjPnfYXnsCuW90N
    3cKnKAbd+nq+eM2G6VKICbt5yE+69PmvqMpDaXTzc+zcNVOFWPQFP92gZH9Bghgd
    czJLp+Hkm/xYDnAdjR0T90yohuv0d/mU9P1lk1LPn51M5Sd17YQow6MbUyqy4M5F
    J5iCBtUKxXotEvvfOFxw6j6ZLWlePWuHIqaWolU5/rmEv6IvoYlpbdLT5cseXbd9
    s6liB+iceTj6RO7JyNa3XxSIa18hYceSftd6zkvPa84fMdAjmbhB5rR/iurIgvnR
    NO6hQ+oaxRXJfLNpH4L+A09cfWK0mCOkqPbJJfMKG/Zn+zcCoKoQyEi9YqZeKIql
    +0iK2NUCgYEAzVdjdYvORWyqGKQD6C0fowuhKtp9g9Jq86kKwihdyxj11dAGOJW8
    i/W8W2DgQpWVkkxdMimnL9+uTAtC+GpS8gHDKxgwTzaq8yBkeE4lSqgUFUsik3+1
    OW0zqJYoi2k3Q2w7p0PScAey6yymeEAbBFY/+BFuhIpoa4vMEko1nW8CgYEA3M7y
    gPIVb6mjQ+M7HFrAArupoivhNUuRqzvGG78BXBhRl5g9NXR0B+QNqO8usRBbp9pp
    tjS9AkttdJKzCQr1Zrh2lAykKbRgMZ3frG6XKZpT/o2zaVRW/oGySXBzS3Uyk7ZH
    LK2x4U959W2N2L8uMyGVq4E9rcApT58L6Wbg9hsCgYEAtzO7iflE/I25qKhU0AXK
    TyamEVzEVSMbxu7PqXBoVjabxrqFgmCdyuVguspQ6zcYLmGxWHrvLfhMQo5dntMF
    0+McpMs89r+Yf7gry2Y1QUl6OZFCdQSgxG6Yg1YNMGycIKxlAJOzIb7Ms6OvlmPj
    dtgY1JOA3gG6rhEY7kyFT0MCgYEAp1vvsE5McxMHnSf4oJgkGq40d6d8jdGWOkwW
    7ubJ2AzSou0Pz5lRbL2soNOQ90GnxsSkBSdZ7whOkOGz83Gr6Mx9i988+iMuGc1I
    QECeMDk52qF6T6ZOPZ7+C+3AZXwR9qVcsv9/6H89uAjuT08wbC7Ta2eM4UnZxfCN
    rb19WusCgYEAs7y1oNKVxC6OVR5GYjsaZPEiyY/ycUrxzbXr+to309nypS631NCp
    K5zSes/L/r5buiN8mlX0A3b33vZ185lp17UIhmhpW/MwjgV+JvJOyWYDIM+gKv5Q
    90AZCsE5lfw35XBViRJ92JsXa3KGbbykwa8qV2gutlJd8CFzpfC1wpw=
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIRAOc+5r2H13i7wYKS4zaBPmIwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDYxOTAyMTAyN1oXDTI2
    MDYxOTAyMTAyN1owNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDBR84DHGaOOg0hpWxHypSTTIOgGqV2FedwMgOzVln9w3Y+Pvn4d0Iyst0u4mDn
    wywtOTyUEmlpzfbbA3qhGXiDvrADSRIzcPRAJRYDlkfdmHe0NqQ6GTLtAFsMQ6Up
    BIxH8vQGiFzMWxaLZ6dxo0SdetDm0g35PXXUAD3Jt5QZEYbH7xIyWKXUkZ4NItYs
    Wvja4SvBDpEBHA56CiyNya1pGgfMYapVPAYkpMW4AgfFo+aCIfQ4dyswOwtSdN1l
    WTVH+pF4ieyVwPJEO6YJX84Xiku2Cn8aZ4p/dqE1m/IjctWSwkL0zf1e+mc1eohd
    Rc4gZFNYaOqQO4MJbnyOMg/jAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME
    GDAWgBRJLcMQFInuUzQeyY4N9ZKjYQ/KDDAdBgNVHREEFjAUghJWZWxvY2lyYXB0
    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBADWtSJA06Jm9h/WHSs3ilE9GdwFo
    RYkbcBW/h8GQatptuZ6sZKiQnhNMggOEtHjlAKZXP6evpfdmyR+Y5Dbi7RcCzd3G
    6S5QS6F0Q7/P8Q6PTrWhaoPQypQJ5K4btLxU77yPky1+/8PrGhaa1M+kO5P91XVv
    z9W3xj22iAZoY6zOn7q75D10KzIkZxehQfbkzdDbZA7SI7YZfRciXdhReUr+l2XE
    hStOuuDcbjRA1tiraBw0N99e12xahT2lXvC4lIH5FDw3LL4w7AuVTknvDowdmnXi
    GWNqOtv3HefS3eKBX09GMynJSaLj+JDpZrE35hDckMJvBoisrHNipJmgIWI=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAwUfOAxxmjjoNIaVsR8qUk0yDoBqldhXncDIDs1ZZ/cN2Pj75
    +HdCMrLdLuJg58MsLTk8lBJpac322wN6oRl4g76wA0kSM3D0QCUWA5ZH3Zh3tDak
    Ohky7QBbDEOlKQSMR/L0BohczFsWi2encaNEnXrQ5tIN+T111AA9ybeUGRGGx+8S
    Mlil1JGeDSLWLFr42uErwQ6RARwOegosjcmtaRoHzGGqVTwGJKTFuAIHxaPmgiH0
    OHcrMDsLUnTdZVk1R/qReInslcDyRDumCV/OF4pLtgp/GmeKf3ahNZvyI3LVksJC
    9M39XvpnNXqIXUXOIGRTWGjqkDuDCW58jjIP4wIDAQABAoIBACw1Tkur3VE+ue4u
    Nhwdm+otIBYowhvGWs9wwSPt5luCr7MBGI/aR0vtWWX15ZBdNeeKJe8AXxgSQhpK
    K2xZtRT9Mqktt3oIpfVeBjD/2KQ40Xho3xti1CEdabXeaxJ8tdFnIqWz3vXnB7sP
    FF+LppAWnV2OQh/2DNNW0ssmsDsjPsoaUFkHx+HyrK0xisH5P1mqJE20nu1D8olb
    8+RyIaJpX3GXqCyp99IA7HkW+9IO7GgiZwx7vtp+2rzqrxzBiiV+jcqn+6NyFBlQ
    0X7taZdHzauulU/A1rCGbOMb0wuumwN3SofaOhJ6FKwG8K7kWDxuuygMDEoSUxXF
    ps6WnkECgYEA91h2oziXzaTUBWSkqOcnGFfPCj3ISTuEFFF+A3frqSgPu22xuSau
    jwu45+UiZOy6oQzocGldBuPc4enmDUzTPtph8gGUDF7gsIcgJqny06osU30gdHBr
    RBHEVnB9+XZZMLAhzxZfQPkiYPT/MZcy9Nctly6puI0l4hWzdwhW/HECgYEAyAsR
    GoTM9E01M0j9Ggx4IefFjbASUXCh64RrR+vsU5+iq9HXxalXY0mMBC5I2wQsnoTa
    tiPUcMUL289Gb4MLiB7R+7Mc+sNu5oSht5kZj2eAp+4bp0xTrEr5jT7n1NIY4Xoa
    mEs9sGWi5F3/0X/dgwdPZxnguxzT5ILdv5nqS5MCgYAm2OEBL6E/7hRSqITn9i4A
    t8HPtPZg8hUDb+0ftFTx41XdNRRFpRqjYs7utOEbAscpBjL3fMTckSse3DKCgj9n
    Trs1XCQZcUlO0FovWF/H+KEvl6ZiQ0nFjhjNDqvqYzkM2Yzlzni1ZquMmM3/xuR8
    6dLCPNTxJFH/2TKvjkLDMQKBgHHiSwRr4jqa0dS2ktEHlETJLCCzwln241evdVvm
    pg4dbYCf4FU5SPTPZBTlPLjjMXu1asYSs9jXdR7Ya+MEGcaOtUC0AaWJKVO24lIh
    qPmJFSeFWNzviRsnO9b7nwP78Ao9d3KIM0B/PDMCiKb+Ql9cBApQIy6jBMas8g0o
    VMhdAoGAUI6dmRA/q+3446XBioZ1Kr9tYmjMhaSDAk1Gxeq6ihLOHSuR44V+qvc9
    CKGWV+Ng5/GugI5PxOeiap6Y0BeYN8LNExNpbbv67w/cQfqNtIH/ljXCrVkAqVVZ
    0qSzeqVjFZManlB/efYuJ0ZYn4jkg1qIZ51CMW0hxDumeERfKEs=
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /var/tmp/velociraptor/
  filestore_directory: /var/tmp/velociraptor/
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 0.0.0.0
  bind_port: 8003
api_config: {}
obfuscation_nonce: Ezp86VOpeWg=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
