# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.0
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - OPENSEARCH_SSL_VERIFICATION_MODE=full
      - CLUSTER_DISABLED=yes
      - METADATA_SERVER=no
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_cluster/wazuh_manager.conf:/var/ossec/etc/ossec.conf
      - ./config/wazuh_cluster/local_internal_options.conf:/var/ossec/etc/local_internal_options.conf
    healthcheck:
      test: ["CMD", "wazuh-control", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      wazuh.indexer:
        condition: service_healthy

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.0
    hostname: wazuh.indexer
    restart: unless-stopped
    ports:
      - "9200:9200"  
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_INITIAL_ADMIN_USER=${OPENSEARCH_ADMIN_USER}
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_HTTP_PORT=9200
      - OPENSEARCH_HTTPS_PORT=9243
      - DISABLE_SECURITY_PLUGIN=false
      - DISABLE_INSTALL_DEMO_CONFIG=false
      - OPENSEARCH_SECURITY_SSL_TRANSPORT_ENABLED=true
      - OPENSEARCH_SECURITY_SSL_HTTP_ENABLED=true
      - OPENSEARCH_SECURITY_SSL_TRANSPORT_VERIFICATION_MODE=FULL
      - OPENSEARCH_SECURITY_SSL_HTTP_VERIFICATION_MODE=FULL
      - OPENSEARCH_SECURITY_SSL_TRANSPORT_KEYSTORE_FILE=/usr/share/wazuh-indexer/certs/keystore.jks
      - OPENSEARCH_SECURITY_SSL_TRANSPORT_TRUSTSTORE_FILE=/usr/share/wazuh-indexer/certs/truststore.jks
      - OPENSEARCH_SECURITY_SSL_HTTP_KEYSTORE_FILE=/usr/share/wazuh-indexer/certs/keystore.jks
      - OPENSEARCH_SECURITY_SSL_HTTP_TRUSTSTORE_FILE=/usr/share/wazuh-indexer/certs/truststore.jks
    volumes:
      - ./data/wazuh/indexer/data:/var/lib/wazuh-indexer
      - ./data/wazuh/indexer/logs:/var/log/wazuh-indexer
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
      - ./config/wazuh_indexer/opensearch.yml:/usr/share/wazuh-indexer/config/opensearch.yml
      - ./data/wazuh/indexer/certs:/usr/share/wazuh-indexer/certs
      - ./config/wazuh_indexer/roles.yml:/usr/share/wazuh-indexer/opensearch-security/roles.yml
      - ./config/wazuh_indexer/roles_mapping.yml:/usr/share/wazuh-indexer/opensearch-security/roles_mapping.yml
      - ./config/wazuh_indexer/action_groups.yml:/usr/share/wazuh-indexer/opensearch-security/action_groups.yml
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 2G
    security_opt:
      - no-new-privileges:true

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    hostname: wazuh.dashboard
    restart: unless-stopped
    ports:
      - "443:443"  
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager:55000
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=SecretPassword
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - OPENSEARCH_SSL_VERIFICATION_MODE=full
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - OPENSEARCH_URL=https://wazuh.indexer:9200
    volumes:
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - ./data/wazuh/dashboard/certs:/usr/share/wazuh-dashboard/certs
    depends_on:
      wazuh.indexer:
        condition: service_healthy
      wazuh.manager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
