version: '3.8'

services:
  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: soc-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-app:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      - thehive
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  thehive:
    external: true
    name: home-soc-lab_thehive
