version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - thehive
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "DESCRIBE keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - http.port=9200
      - http.publish_port=9200
      - transport.port=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - thehive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 2G

  thehive:
    image: strangebee/thehive:5.2
    depends_on:
      cassandra:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_ENDPOINTS=cassandra
      - CASSANDRA_KEYSPACE=thehive
      - SEARCH_ENGINE=elasticsearch
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=thehive
      - SECRET=changeme
      - APPLICATION_SECRET=changeme
      - PLAY_HTTP_SECRET=changeme
      - PLAY_CRYPTO_SECRET=changeme
      - AUTHENTICATION_METHOD=basic
      - AUTHENTICATION_BASIC_USERNAME=admin
      - AUTHENTICATION_BASIC_PASSWORD=changeme
      - http.port=9000
      - http.host=0.0.0.0
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped
    stop_grace_period: 60s
    stop_signal: SIGTERM
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - thehive_data:/opt/thp/thehive/index
      - thehive_config:/etc/thehive
      - thehive_data2:/opt/thp/thehive/data
    networks:
      - thehive

  nginx:
    image: nginx:alpine
    container_name: thehive-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/acme:/var/www/certbot
    environment:
      - TZ=UTC
    depends_on:
      - thehive
    networks:
      - thehive
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  thehive:
    driver: bridge

volumes:
  cassandra_data:
  es_data:
  thehive_data:
  thehive_config:
  thehive_data2:
