FROM alpine:3.16

# Install required packages
RUN apk add --no-cache openssl

# Create a directory for the certificates
RUN mkdir -p /certs

# Copy the certificate generation script
COPY gen_certs_docker.sh /gen_certs_docker.sh
RUN chmod +x /gen_certs_docker.sh

# Set the working directory
WORKDIR /certs

# Run the certificate generation script
ENTRYPOINT ["/gen_certs_docker.sh"]
