version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - thehive
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "DESCRIBE keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9202
      - http.publish_port=9202
      - transport.port=9301
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9202:9202"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - thehive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9202/_cluster/health?wait_for_status=yellow"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 2G

  thehive:
    image: strangebee/thehive:5.2
    depends_on:
      cassandra:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_ENDPOINTS=cassandra
      - CASSANDRA_KEYSPACE=thehive
      - SEARCH_ENGINE=elasticsearch
      - ELASTICSEARCH_URI=http://elasticsearch:9202
      - ELASTICSEARCH_INDEX=thehive
      - SECRET=changeme
      - APPLICATION_SECRET=changeme
      - PLAY_HTTP_SECRET=changeme
      - PLAY_CRYPTO_SECRET=changeme
      - AUTHENTICATION_METHOD=basic
      - AUTHENTICATION_BASIC_USERNAME=admin
      - AUTHENTICATION_BASIC_PASSWORD=changeme
      - http.port=9000
      - http.host=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    expose:
      - "9000"
    volumes:
      - thehive_data:/opt/thp/thehive/index
      - thehive_config:/etc/thehive
      - thehive_data2:/opt/thp/thehive/data
    networks:
      - thehive
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thehive.rule=Host(`thehive.localhost`)"
      - "traefik.http.routers.thehive.entrypoints=websecure"
      - "traefik.http.routers.thehive.tls.certresolver=myresolver"
      - "traefik.http.services.thehive.loadbalancer.server.port=9000"
    restart: unless-stopped

networks:
  thehive:
    driver: bridge
    external: true

volumes:
  cassandra_data:
  es_data:
  thehive_data:
  thehive_config:
  thehive_data2:
