version: '3.8'

services:
  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: soc-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-app:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=2000
      - PYTHONUNBUFFERED=true
    networks:
      - thehive
    restart: unless-stopped
    stop_grace_period: 30s
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 512M

networks:
  thehive:
    external: true
    name: thehive
