apiVersion: 1

datasources:
  # Main Elasticsearch datasource for SOC
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch-soc:9200
    database: '[wazuh-]YYYY.MM.DD'
    jsonData:
      esVersion: 8.0.0
      timeField: '@timestamp'
      interval: Daily
      timeInterval: '1m'
      logMessageField: 'message'
      logLevelField: 'level'
    secureJsonData:
      httpHeaderValue1: 'Basic ZWxhc3RpYzpZb3VyU2VjdXJlUGFzc3dvcmQxMjMh'
    version: 1
    editable: true
    isDefault: true

  # Wazuh-specific datasource
  - name: Wazuh
    type: elasticsearch
    access: proxy
    url: http://wazuh.indexer:9200
    database: 'wazuh-alerts-*'
    jsonData:
      esVersion: 7.10.0
      timeField: 'timestamp'
      interval: Daily
      timeInterval: '1m'
      maxConcurrentShardRequests: 5
    version: 1
    editable: true

  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: true
    jsonData:
      timeInterval: '1m'
      httpMethod: 'POST'

  # Loki for logs (if used)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
