version: '3.8'

services:
  # MISP Web Application
  misp:
    image: ghcr.io/misp/misp-docker:2.4.176-1
    container_name: misp
    environment:
      - MYSQL_HOST=misp-db
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp
      - MYSQL_DATABASE=misp
      - MISP_BASE_URL=http://localhost:8080
      - MYSQL_PORT_NUMBER=3306
      - REDIS_FQDN=misp-redis
      - REDIS_PORT=6379
      - MISP_ADMIN_EMAIL=admin@localhost
      - MISP_ADMIN_PASSPHRASE=ChangeThisDefaultPassword123!
      - MISP_ORG=Home-SOC-Lab
      - MISP_EMAIL=admin@localhost
      - MISP_SALT=ChangeThisDefaultSalt123!
      - MISP_SECRET=ChangeThisDefaultSecret123!
      - MYSQL_ROOT_PASSWORD=ChangeThisRootPassword123!
    volumes:
      - misp_data:/var/www/MISP
      - misp_config:/var/www/MISP/app/Config
      - misp_logs:/var/www/MISP/app/tmp/logs
    ports:
      - "8080:80"
    depends_on:
      - misp-db
      - misp-redis
    networks:
      - misp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database (MariaDB)
  misp-db:
    image: mariadb:10.11
    container_name: misp-db
    environment:
      - MYSQL_ROOT_PASSWORD=ChangeThisRootPassword123!
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp
    volumes:
      - misp_db_data:/var/lib/mysql
    networks:
      - misp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Server
  misp-redis:
    image: redis:6.2
    container_name: misp-redis
    command: redis-server --appendonly yes
    volumes:
      - misp_redis_data:/data
    networks:
      - misp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MISP Worker
  misp-worker:
    image: ghcr.io/misp/misp-docker:2.4.176-1
    container_name: misp-worker
    command: /sbin/entrypoint_worker.sh
    environment:
      - MYSQL_HOST=misp-db
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp
      - MYSQL_DATABASE=misp
      - MYSQL_PORT=3306
      - REDIS_FQDN=misp-redis
      - REDIS_PORT=6379
      - MISP_BASE_URL=http://misp
      - MISP_ADMIN_EMAIL=admin@localhost
      - MISP_ADMIN_PASSPHRASE=ChangeThisDefaultPassword123!
      - WORKERS=4
      - WORKER_TIMEOUT=60
    volumes:
      - misp_data:/var/www/MISP
      - misp_config:/var/www/MISP/app/Config
      - misp_logs:/var/www/MISP/app/tmp/logs
    depends_on:
      - misp-db
      - misp-redis
    networks:
      - misp_network
    restart: unless-stopped

  # MISP Modules
  misp-modules:
    image: ghcr.io/misp/misp-modules:latest
    container_name: misp-modules
    environment:
      - MISP_MODULES_DEBUG=0
    volumes:
      - misp_data:/var/www/MISP
    networks:
      - misp_network
    restart: unless-stopped
    depends_on:
      - misp

networks:
  misp_network:
    driver: bridge

volumes:
  misp_data:
  misp_config:
  misp_logs:
  misp_db_data:
  misp_redis_data:
