version: '3.8'

services:
  soc-gui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - certs:/app/certs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - cert-manager

  cert-manager:
    build: ./cert-manager
    ports:
      - "5000:5000"
    volumes:
      - certs:/certs
    environment:
      - FLASK_APP=cert_utils.py
      - FLASK_ENV=production
      - CERT_DIR=/certs

volumes:
  certs:
