services:
  os01:
    image: opensearchproject/opensearch:$OS_VERSION
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    container_name: $OS_NODE1
    environment:
      - node.name=$OS_NODE1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms$OS_JAVA_MEM -Xmx$OS_JAVA_MEM"
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - discovery.type=single-node
    restart: unless-stopped
    networks:
      - cyber-blue

  arkime:
    build:
      context: ../arkime
      dockerfile: Dockerfile
    container_name: arkime
    depends_on:
      - $OS_NODE1
      # uncomment and add all OS node container names
      # - $OS_NODE2
    environment:
      - OS_HOST=$OS_NODE1
      - OS_PORT=9200
    ports:
      - $ARKIME_PORT:8005
    volumes:
      - arkime_config:/data/config
      - arkime_logs:/data/logs
      - type: bind
        source: $PCAP_DIR
        target: /data/pcap
    restart: unless-stopped
    networks:
      - cyber-blue

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
    restart: unless-stopped
    ports:
      - "9210:9200"
      - "9300:9300"
    networks:
      - cyber-blue
