version: '3.7'

services:
  linux-agent:
    container_name: linux-agent
    image: debian:bookworm-slim
    restart: unless-stopped
    networks:
      - siem-stack 
    depends_on:
       # suricata: 
       #   condition: "service_started"
       wazuh.indexer:
          condition: "service_started"
    environment:
      - WAZUH_MANAGER=wazuh.manager
      - WAZUH_AGENT_NAME=debian-bookworm-slim
    command: > 
      sh -c " 
      apt update &&
      apt install -y libsystemd0 systemd procps sudo lsb-release curl wget &&
      wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb &&
      dpkg -i ./wazuh-agent_4.10.1-1_amd64.deb &&
      /var/ossec/bin/wazuh-control start &&
      tail -f /var/ossec/logs/ossec.log 
      "

    # command: > 
    #   sh -c " 
    #   apt update &&
    #   apt install -y libsystemd0 systemd procps sudo lsb-release curl wget net-tools suricata nano &&
    #   wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb &&
    #   dpkg -i ./wazuh-agent_4.10.1-1_amd64.deb &&
    #
    #   cd /tmp/ && curl -LO https://rules.emergingthreats.net/open/suricata-6.0.8/emerging.rules.tar.gz &&
    #   tar -xvzf emerging.rules.tar.gz && mkdir /etc/suricata/rules && mv rules/*.rules /etc/suricata/rules/ &&
    #   chmod 640 /etc/suricata/rules/*.rules && suricata-update &&
    #
    #   /var/ossec/bin/wazuh-control start &&
    #   tail -f /var/ossec/logs/ossec.log 
    #   "
    #
    # volumes:
    #  # - suricata-logs:/var/log/suricata/
    #  - ./nids/suricata/suricata.yaml:/etc/suricata/suricata.yaml



networks:
  siem-stack:
    external: true

# volumes:
#   suricata-logs:
#
