_meta:
  type: "internalusers"
  config_version: 2

# Define your internal users here
admin:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "admin"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"

kibanaserver:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "kibanaserver"
  reserved: true
  description: "Kibana server user"

kibanaro:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "kibanaro"
  reserved: false
  backend_roles:
  - "kibanauser"
  - "readall"
  description: "Kibana read-only user"

logstash:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "logstash"
  reserved: false
  backend_roles:
  - "logstash"
  description: "Logstash user"

readall:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "readall"
  reserved: false
  description: "Read-only user"

snapshotrestore:
  hash: "$2y$12$BBAE/SnXD5uzHNXVY2iQ8eH5zO8wHmQQAEIHHXjI4sOD2LD9D1N1y"  # password is "snapshotrestore"
  reserved: false
  backend_roles:
  - "snapshotrestore"
  description: "Snapshot restore user"
