cluster.name: wazuh-cluster
node.name: wazuh-indexer
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer
network.host: 0.0.0.0
discovery.type: single-node
http.port: 9200
transport.port: 9600
bootstrap.memory_lock: true

# Security configuration
plugins.security.disabled: false
plugins.security.ssl.http.enabled: false
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - "CN=admin"

# Performance settings
thread_pool:
  write:
    size: 16
    queue_size: 10000

# Initialize security index on first run
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.nodes_dn:
  - "CN=wazuh-indexer"

# Disable security audit to reduce overhead
plugins.security.audit.type: noop

# Disable security plugin features we don't need
plugins.security.check_snapshot_restore_write_privileges: false
plugins.security.restapi.roles_enabled: []
plugins.security.system_indices.enabled: false

# Disable security for internal cluster communication
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemkey_filepath: node1.pem
plugins.security.ssl.transport.pemcert_filepath: node1.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.http.enabled: false

# Disable security for demo purposes
plugins.security.unsupported.inject_user_enabled: true
plugins.security.unsupported.inject_user_password: admin
plugins.security.unsupported.inject_user_roles: "admin"

# Disable security for demo purposes
opendistro_security.disabled: false
opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.audit.type: noop
opendistro_security.check_snapshot_restore_write_privileges: false
opendistro_security.restapi.roles_enabled: []
opendistro_security.system_indices.enabled: false
