version: '3.8'

services:
  faiss-service:
    image: milvusdb/milvus:v2.0.0-rc5 # Using Milvus which includes FAISS
    container_name: faiss-service
    environment:
      - ETCD_ENABLED=true
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/etcd
      - MINIO_ENABLED=true
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - COMMON_STORAGETYPE=minio
      - COMMON_BUCKETNUM=1
      - COMMON_METACACHE_ENABLED=true
      - COMMON_METACACHE_SIZE=64MB
      - MSGSTREAM_UNITTESTCHANNELNUM=1
      - MSGSTREAM_UNITTESTCHANNELSUFFIX=0
      - METRIC_ENABLE_MONITOR=true
    volumes:
      - faiss_data:/var/lib/milvus
      - faiss_config:/var/lib/milvus/conf
    ports:
      - "19530:19530"  # gRPC port
      - "19121:19121"  # HTTP port
    networks:
      - thehive
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19121/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data
    networks:
      - thehive
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  faiss-web:
    image: milvusbootcamp/faiss-webclient:2.0.0
    container_name: faiss-web
    ports:
      - "3001:80"
    environment:
      - API_URL=http://faiss-service:19121
    depends_on:
      - faiss-service
    networks:
      - thehive
    restart: unless-stopped

networks:
  thehive:
    external: true
    name: home-soc-lab_thehive

volumes:
  faiss_data:
  faiss_config:
  minio_data:
